# Generated by Django 6.0 on 2026-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Имя/код шаблона (уникально)', max_length=255, unique=True)),
                ('html_template', models.TextField(blank=True, default='', help_text='HTML-шаблон (большой)')),
                ('html_content', models.TextField(blank=True, default='', help_text='HTML-контент (большой)')),
                ('styles', models.JSONField(blank=True, default=dict, help_text='Стили/настройки (JSON)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'panel_global_templates',
                'ordering': ['order', 'template_name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='panel_globa_is_acti_3d44b5_idx')],
            },
        ),
    ]
