# Generated by Django 6.0 on 2026-01-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltemplate',
            name='buttons',
            field=models.JSONField(blank=True, default=dict, help_text='Кнопки/настройки (JSON)'),
        ),
    ]
