# Generated by Django 6.0 on 2025-12-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True, help_text='UUID воркспейса (такой же, как в workspace_link у пользователя)')),
                ('name', models.CharField(help_text='Название подключения, видно только внутри панели', max_length=255)),
                ('soft_deleted', models.BooleanField(default=False, help_text='Если включено — подключение скрыто, но не удалено')),
                ('smtp_config', models.JSONField(blank=True, default=dict, help_text='Настройки SMTP (host, port, encryption, username, password, ...)')),
                ('smtp_status', models.CharField(default='not_checked', max_length=32)),
                ('imap_config', models.JSONField(blank=True, default=dict, help_text='Настройки IMAP (host, port, encryption, username, password, folders, ...)')),
                ('imap_status', models.CharField(default='not_checked', max_length=32)),
                ('from_email', models.EmailField(help_text='E-mail отправителя (From:)', max_length=254)),
                ('from_name', models.CharField(help_text='Отображаемое имя отправителя', max_length=255)),
                ('status', models.CharField(default='not_checked', help_text='Общий статус подключения (меняется только кодом)', max_length=32)),
                ('last_check_payload', models.JSONField(blank=True, default=dict, help_text='Сырой JSON результата последней проверки')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Когда последний раз проверяли подключение', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace_id', 'soft_deleted'], name='aap_setting_workspa_01653c_idx')],
            },
        ),
    ]
