# Generated by Django 6.0 on 2025-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='task_client',
            field=models.TextField(blank=True, default=''),
        ),
    ]
