# Generated by Django 6.0 on 2025-12-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0002_audiencetask_task_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='run_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='subscribers_limit',
            field=models.IntegerField(default=500),
        ),
    ]
