# Generated by Django 6.0 on 2025-12-21 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('task', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('task_branches', models.TextField()),
                ('task_geo', models.TextField()),
                ('task_client', models.TextField(blank=True, default='')),
                ('run_processing', models.BooleanField(default=False)),
                ('subscribers_limit', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aap_audience_audiencetask',
                'ordering': ['-created_at'],
            },
        ),
    ]
