# Generated by Django 6.0 on 2025-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='sell', max_length=4),
        ),
    ]
