# Generated by Django 6.0 on 2026-01-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0002_audiencetask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audiencetask',
            name='subscribers_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
