# Generated by Django 6.0 on 2026-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0003_audiencetask_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencetask',
            name='subscribers_limit',
            field=models.IntegerField(default=0),
        ),
    ]
