# Generated by Django 6.0 on 2026-03-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0004_alter_audiencetask_subscribers_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='source_company',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='source_geo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='source_product',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='target_branches',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='target_contact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='target_geo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
