# Generated by Django 6.0 on 2026-03-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0005_audiencetask_source_company_audiencetask_source_geo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencetask',
            name='target_branches',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='target_contact',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='target_geo',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='audiencetask',
                    name='collected',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
