# Generated by Django 6.0 on 2026-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0006_remove_audiencetask_target_branches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
