# Generated by Django 6.0 on 2026-04-04 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0008_audiencetask_rating_branch_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetask',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='rate_limit',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='audiencetask',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
    ]
