# Generated by Django 6.0 on 2026-04-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0009_audiencetask_active_audiencetask_rate_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencetask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='task_branches',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='task_client',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='task_geo',
        ),
    ]
