# Generated by Django 6.0 on 2026-04-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_audience', '0010_remove_audiencetask_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencetask',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='run_processing',
        ),
        migrations.RemoveField(
            model_name='audiencetask',
            name='subscribers_limit',
        ),
    ]
