# Generated by Django 6.0 on 2026-02-23 00:14

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import mailer_web.models_accounts
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("public", "0003_alter_clientuser_managers"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="ClientUser",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("password", models.CharField(max_length=128, verbose_name="password")),
                        ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                        (
                            "username",
                            models.CharField(
                                error_messages={"unique": "A user with that username already exists."},
                                max_length=150,
                                unique=True,
                                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                            ),
                        ),
                        ("first_name", models.CharField(blank=True, max_length=150)),
                        ("last_name", models.CharField(blank=True, max_length=150)),
                        ("email", models.EmailField(blank=True, max_length=254)),
                        ("is_active", models.BooleanField(default=True)),
                        ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                    ],
                    options={
                        "db_table": "accounts_clientuser",
                    },
                    managers=[
                        ("objects", mailer_web.models_accounts.ClientUserManager()),
                    ],
                ),
                migrations.CreateModel(
                    name="UserWorkspace",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("workspace_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="workspace_link",
                                to="mailer_web.clientuser",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "accounts_userworkspace",
                    },
                ),
            ],
        ),
    ]
