# Generated by Django 6.0 on 2026-02-23 00:14

from django.db import migrations


FORWARD_SQL = """
DO $$
BEGIN
    IF to_regclass('public.accounts_clientuser') IS NULL
       AND to_regclass('public.public_clientuser') IS NOT NULL THEN
        ALTER TABLE public_clientuser RENAME TO accounts_clientuser;
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('public.public_clientuser_id_seq') IS NOT NULL
       AND to_regclass('public.accounts_clientuser_id_seq') IS NULL THEN
        ALTER SEQUENCE public_clientuser_id_seq RENAME TO accounts_clientuser_id_seq;
    END IF;
END
$$;

ALTER TABLE IF EXISTS accounts_clientuser DROP COLUMN IF EXISTS is_staff;
ALTER TABLE IF EXISTS accounts_clientuser DROP COLUMN IF EXISTS is_superuser;

DROP TABLE IF EXISTS public_clientuser_groups;
DROP TABLE IF EXISTS public_clientuser_user_permissions;
DROP TABLE IF EXISTS accounts_frontuser CASCADE;

DO $$
DECLARE
    old_ct_id integer;
    new_ct_id integer;
BEGIN
    SELECT id INTO old_ct_id
    FROM django_content_type
    WHERE app_label = 'public' AND model = 'clientuser'
    LIMIT 1;

    SELECT id INTO new_ct_id
    FROM django_content_type
    WHERE app_label = 'mailer_web' AND model = 'clientuser'
    LIMIT 1;

    IF old_ct_id IS NOT NULL AND new_ct_id IS NULL THEN
        UPDATE django_content_type
        SET app_label = 'mailer_web'
        WHERE id = old_ct_id;
    ELSIF old_ct_id IS NOT NULL AND new_ct_id IS NOT NULL THEN
        UPDATE auth_permission SET content_type_id = new_ct_id WHERE content_type_id = old_ct_id;
        UPDATE django_admin_log SET content_type_id = new_ct_id WHERE content_type_id = old_ct_id;
        DELETE FROM django_content_type WHERE id = old_ct_id;
    END IF;
END
$$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("mailer_web", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=migrations.RunSQL.noop),
    ]
