# Generated by Django 6.0 on 2026-03-07

from uuid import uuid4

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def _forward_migrate_workspace_links(apps, schema_editor):
    ClientUser = apps.get_model("mailer_web", "ClientUser")
    Workspace = apps.get_model("mailer_web", "Workspace")
    UserWorkspace = apps.get_model("mailer_web", "UserWorkspace")

    # перенос существующих связей (accounts_userworkspace -> accounts_workspaces + accounts_clientuser.workspace_id)
    for row in UserWorkspace.objects.all().only("user_id", "workspace_id").iterator():
        ws, _unused = Workspace.objects.get_or_create(
            id=row.workspace_id,
            defaults={
                "company_name": "",
                "company_address": "",
                "company_phone": "",
                "company_email": "",
                "access_type": "full",
                "created_at": timezone.now(),
            },
        )
        ClientUser.objects.filter(id=row.user_id).update(workspace_id=ws.id)

    # safety-net: если у пользователя не было accounts_userworkspace, создаём новый workspace
    for user in ClientUser.objects.filter(workspace_id__isnull=True).only("id").iterator():
        ws = Workspace.objects.create(access_type="full")
        ClientUser.objects.filter(id=user.id).update(workspace_id=ws.id)


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0002_rehome_clientuser_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False)),
                ("company_name", models.CharField(blank=True, default="", max_length=255)),
                ("company_address", models.TextField(blank=True, default="")),
                ("company_phone", models.CharField(blank=True, default="", max_length=64)),
                ("company_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("full", "full"), ("test", "test"), ("stat_only", "stat_only")],
                        db_index=True,
                        default="full",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_workspaces",
            },
        ),
        migrations.AddField(
            model_name="clientuser",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="position",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="role",
            field=models.CharField(
                choices=[("main", "main"), ("viewer", "viewer")],
                db_index=True,
                default="main",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="mailer_web.workspace",
            ),
        ),
        migrations.RunPython(_forward_migrate_workspace_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clientuser",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="mailer_web.workspace",
            ),
        ),
        migrations.DeleteModel(
            name="UserWorkspace",
        ),
    ]
