# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0003_workspace_company_and_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuser",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="workspace",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
