# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


def _fill_empty_company_names(apps, schema_editor):
    Workspace = apps.get_model("mailer_web", "Workspace")
    qs = Workspace.objects.filter(company_name__isnull=True) | Workspace.objects.filter(company_name="")
    for ws in qs.iterator():
        ws.company_name = f"Компания {ws.id}"
        ws.save(update_fields=["company_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0004_workspace_clientuser_archived"),
    ]

    operations = [
        migrations.RunPython(_fill_empty_company_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="workspace",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
    ]
