# Generated by Django 6.0 on 2026-03-07

from django.db import migrations


def _fill_empty_company_names(apps, schema_editor):
    Workspace = apps.get_model("mailer_web", "Workspace")
    for ws in Workspace.objects.all().only("id", "company_name").iterator():
        if (ws.company_name or "").strip():
            continue
        ws.company_name = f"Компания {ws.id}"
        ws.save(update_fields=["company_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0005_workspace_company_name_required"),
    ]

    operations = [
        migrations.RunPython(_fill_empty_company_names, migrations.RunPython.noop),
    ]
