# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0006_fill_empty_workspace_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientuser",
            name="role",
            field=models.CharField(
                choices=[("main", "main"), ("super", "super"), ("viewer", "viewer")],
                db_index=True,
                default="main",
                max_length=32,
            ),
        ),
    ]
