# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


def _normalize_user_role_super(apps, schema_editor):
    ClientUser = apps.get_model("mailer_web", "ClientUser")
    ClientUser.objects.filter(role="super").update(role="main")


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0007_clientuser_role_super"),
    ]

    operations = [
        migrations.RunPython(_normalize_user_role_super, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clientuser",
            name="role",
            field=models.CharField(
                choices=[("main", "main"), ("viewer", "viewer")],
                db_index=True,
                default="main",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="access_type",
            field=models.CharField(
                choices=[("full", "full"), ("test", "test"), ("stat_only", "stat_only"), ("super", "super")],
                db_index=True,
                default="full",
                max_length=32,
            ),
        ),
    ]
