# Generated by Django 6.0 on 2026-03-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0008_workspace_access_super_and_drop_user_super"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientuser",
            name="is_active",
        ),
    ]
