# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


def _normalize_emails(apps, schema_editor):
    ClientUser = apps.get_model("mailer_web", "ClientUser")
    used: set[str] = set()

    for user in ClientUser.objects.all().order_by("id").only("id", "email", "username").iterator():
        email = (user.email or "").strip().lower()
        legacy = (user.username or "").strip().lower()

        if not email:
            if legacy and "@" in legacy:
                email = legacy
            elif legacy:
                email = f"{legacy}@legacy.local"
            else:
                email = f"user{user.id}@legacy.local"

        if "@" not in email:
            email = f"{email}@legacy.local"

        local, domain = email.split("@", 1)
        local = (local or f"user{user.id}").strip() or f"user{user.id}"
        domain = (domain or "legacy.local").strip() or "legacy.local"

        candidate = f"{local}@{domain}".lower()
        idx = 1
        while candidate in used:
            idx += 1
            candidate = f"{local}+{idx}@{domain}".lower()

        used.add(candidate)
        if user.email != candidate:
            user.email = candidate
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0009_remove_clientuser_is_active"),
    ]

    operations = [
        migrations.RunPython(_normalize_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clientuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name="clientuser",
            name="username",
        ),
    ]
