# Generated by Django 6.0 on 2026-03-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_web', '0011_mailletter_mailtemplate_alter_clientuser_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailletter',
            name='html',
        ),
        migrations.AddField(
            model_name='mailletter',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='MailLetterLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=16)),
                ('letter_html', models.TextField(blank=True, default='')),
                ('send_html', models.TextField(blank=True, default='')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='mailer_web.mailletter')),
            ],
            options={
                'db_table': 'mailer_web_mail_letter_langs',
                'ordering': ['letter_id', 'lang', 'id'],
            },
        ),
    ]
