# Generated by Django 6.0 on 2026-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_web', '0012_remove_mailletter_html_mailletter_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailletter',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
