# Generated by Django 6.0 on 2026-03-07 16:52

import django.db.models.deletion
from django.db import migrations, models


def _set_default_template_for_letters(apps, schema_editor):
    MailLetter = apps.get_model("mailer_web", "MailLetter")
    MailTemplate = apps.get_model("mailer_web", "MailTemplate")

    tpl = MailTemplate.objects.order_by("id").first()
    if not tpl:
        return

    MailLetter.objects.filter(template_id__isnull=True).update(template_id=tpl.id)


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_web', '0013_mailletter_subject_alter_clientuser_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailletter',
            name='subject',
        ),
        migrations.AddField(
            model_name='mailletter',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='mailer_web.mailtemplate'),
        ),
        migrations.AddField(
            model_name='mailletterlang',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(_set_default_template_for_letters, migrations.RunPython.noop),
    ]
