# Generated by Django 6.0 on 2026-03-07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0014_remove_mailletter_subject_mailletter_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuser",
            name="email_confirmed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="UserActionToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("email_confirm", "email_confirm"), ("password_reset", "password_reset")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_tokens",
                        to="mailer_web.clientuser",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_action_token",
                "indexes": [
                    models.Index(fields=["user", "action", "created_at"], name="accounts_use_user_id_e3d13f_idx"),
                    models.Index(fields=["action", "used_at", "expires_at"], name="accounts_use_action_4cb765_idx"),
                ],
            },
        ),
    ]
