# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0015_clientuser_email_confirmed_and_useractiontoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="access_type",
            field=models.CharField(
                choices=[("full", "full"), ("test", "test"), ("stat_only", "stat_only"), ("super", "super")],
                db_index=True,
                default="test",
                max_length=32,
            ),
        ),
    ]
