# Generated by Django 6.0 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0016_alter_workspace_access_type_default_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("full", "full"),
                    ("test", "test"),
                    ("stat_only", "stat_only"),
                    ("closed", "closed"),
                    ("super", "super"),
                    ("custom", "custom"),
                ],
                db_index=True,
                default="test",
                max_length=32,
            ),
        ),
    ]
