# Generated by Django 6.0 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0017_alter_workspace_access_type_add_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="billing_day",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25)],
                default=1,
            ),
        ),
    ]
