# Generated by Django 6.0 on 2026-04-04

from django.db import migrations, models
from django.utils import timezone


def _fill_workspace_registration_date(apps, schema_editor):
    Workspace = apps.get_model("mailer_web", "Workspace")

    for ws in Workspace.objects.all().only("id", "created_at").iterator():
        created_at = getattr(ws, "created_at", None)
        date_value = timezone.localdate(created_at) if created_at else timezone.localdate()
        Workspace.objects.filter(pk=ws.pk, registration_date__isnull=True).update(
            registration_date=date_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0018_workspace_billing_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="registration_date",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(_fill_workspace_registration_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="workspace",
            name="registration_date",
            field=models.DateField(default=timezone.localdate),
        ),
    ]
