# Generated by Django 6.0 on 2026-04-04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0019_workspace_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE accounts_workspaces
                SET registration_date = created_at
                WHERE created_at IS NOT NULL
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
