# Generated by Django 6.0 on 2026-04-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_web", "0020_alter_workspace_registration_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractiontoken",
            old_name="accounts_use_user_id_e3d13f_idx",
            new_name="accounts_us_user_id_216c11_idx",
        ),
        migrations.RenameIndex(
            model_name="useractiontoken",
            old_name="accounts_use_action_4cb765_idx",
            new_name="accounts_us_action_22a5ac_idx",
        ),
    ]
