# Generated by Django 6.0 on 2026-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer_web', '0021_rename_useractiontoken_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('full', 'full'), ('test', 'test'), ('stat_only', 'stat_only'), ('closed', 'closed'), ('super', 'super'), ('custom', 'custom')], db_index=True, max_length=32, null=True)),
                ('sending_workspace_limit', models.IntegerField(blank=True, null=True)),
                ('sending_task_limit', models.IntegerField(blank=True, null=True)),
                ('active_tasks_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_workspace_limits',
            },
        ),
    ]
