# Generated by Django 6.0 on 2026-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
