# Generated by Django 6.0 on 2026-01-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True, help_text='UUID воркспейса')),
                ('name', models.CharField(help_text='Название ящика (для UI)', max_length=255)),
                ('email', models.EmailField(help_text='Полный email адрес', max_length=254)),
                ('domain', models.CharField(help_text='Домен email (для DNS-проверок)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Если false — ящик полностью выключен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aap_settings_mailboxes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace_id', 'is_active'], name='aap_setting_workspa_da9440_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'email'), name='aap_settings_mailbox_ws_email_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProviderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Стабильный код провайдера (gmail, ionos, …). Может иметь 2 записи: smtp + imap.', max_length=64)),
                ('name', models.CharField(help_text='Отображаемое имя провайдера', max_length=255)),
                ('kind', models.CharField(choices=[('smtp', 'SMTP'), ('imap', 'IMAP')], max_length=8)),
                ('host', models.CharField(max_length=255)),
                ('ports_json', models.JSONField(help_text='Список портов, например [587, 465]')),
                ('security', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL'), ('starttls', 'STARTTLS')], default='none', max_length=16)),
                ('auth_type', models.CharField(choices=[('login', 'Login'), ('oauth2', 'OAuth2')], default='login', max_length=16)),
                ('extra_json', models.JSONField(blank=True, default=dict, help_text='Дефолты/подсказки (например IMAP folders)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'aap_settings_provider_presets',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='aap_setting_is_acti_53112a_idx'), models.Index(fields=['code', 'kind'], name='aap_setting_code_50c70c_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'kind'), name='aap_settings_provider_preset_code_kind_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MailboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('smtp', 'SMTP'), ('imap', 'IMAP')], max_length=8)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('security', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL'), ('starttls', 'STARTTLS')], default='none', max_length=16)),
                ('auth_type', models.CharField(choices=[('login', 'Login'), ('oauth2', 'OAuth2')], default='login', max_length=16)),
                ('username', models.CharField(max_length=255)),
                ('secret_enc', models.TextField(help_text='Зашифрованный пароль или refresh_token')),
                ('extra_json', models.JSONField(blank=True, default=dict, help_text='SMTP/IMAP-специфичные опции (SMTP: from_email/from_name; IMAP: folders/idle и т.п.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='aap_settings.mailbox')),
            ],
            options={
                'db_table': 'aap_settings_mailbox_connections',
                'indexes': [models.Index(fields=['mailbox', 'kind'], name='aap_setting_mailbox_bb6893_idx')],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'kind'), name='aap_settings_mailbox_conn_kind_uniq')],
            },
        ),
    ]
