# Generated by Django 6.0 on 2026-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mailbox',
            name='aap_settings_mailbox_ws_email_uniq',
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['email'], name='aap_setting_email_b19292_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'name'), name='aap_settings_mailbox_ws_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(fields=('email',), name='aap_settings_mailbox_email_uniq'),
        ),
    ]
