# Generated by Django 6.0 on 2026-01-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0002_remove_mailbox_aap_settings_mailbox_ws_email_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='limit_hour_sent',
            field=models.IntegerField(default=50, help_text='Лимит исходящих писем в час'),
        ),
    ]
