# Generated by Django 6.0 on 2026-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0003_mailbox_limit_hour_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.UUIDField(db_index=True, help_text='UUID workspace (1 запись на workspace)', unique=True)),
                ('value_json', models.JSONField(blank=True, default=dict, help_text='Глобальные настройки отправки (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aap_settings_sending_settings',
            },
        ),
    ]
