# Generated by Django 6.0 on 2026-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0004_sendingsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendingsettings',
            old_name='workspace',
            new_name='workspace_id',
        ),
        migrations.AlterField(
            model_name='providerpreset',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='providerpreset',
            name='extra_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='providerpreset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='providerpreset',
            name='ports_json',
            field=models.JSONField(),
        ),
    ]
