# Generated by Django 6.0 on 2026-01-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0005_rename_workspace_sendingsettings_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'ordering': ['email']},
        ),
        migrations.RemoveConstraint(
            model_name='mailbox',
            name='aap_settings_mailbox_ws_name_uniq',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='name',
        ),
    ]
