# Generated by Django 6.0 on 2026-01-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0006_alter_mailbox_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxconnection',
            name='auth_type',
            field=models.CharField(choices=[('login', 'Login'), ('google_oauth2', 'Google OAuth2'), ('microsoft_oauth2', 'Microsoft OAuth2')], default='login', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerpreset',
            name='auth_type',
            field=models.CharField(choices=[('login', 'Login'), ('google_oauth2', 'Google OAuth2'), ('microsoft_oauth2', 'Microsoft OAuth2')], default='login', max_length=16),
        ),
    ]
