# Generated by Django 6.0 on 2026-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0007_alter_mailboxconnection_auth_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxOAuthApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True, help_text='UUID воркспейса')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=16)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret_enc', models.TextField(help_text='Зашифрованный client_secret')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aap_settings_mailbox_oauth_apps',
                'indexes': [models.Index(fields=['workspace_id', 'provider', 'is_active'], name='aap_setting_workspa_149e4f_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'provider'), name='aap_settings_oauth_app_ws_provider_uniq')],
            },
        ),
    ]
