# Generated by Django 6.0 on 2026-01-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0008_mailboxoauthapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImapMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('login', 'Login'), ('google_oauth2', 'Google OAuth2'), ('microsoft_oauth2', 'Microsoft OAuth2')], default='login', max_length=32)),
                ('credentials_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aap_settings_imap_mailboxes',
            },
        ),
        migrations.CreateModel(
            name='SmtpMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('login', 'Login'), ('google_oauth2', 'Google OAuth2'), ('microsoft_oauth2', 'Microsoft OAuth2')], default='login', max_length=32)),
                ('credentials_json', models.JSONField(default=dict)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('limit_hour_sent', models.PositiveIntegerField(default=50)),
                ('extra_headers_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aap_settings_smtp_mailboxes',
            },
        ),
        migrations.RemoveIndex(
            model_name='mailboxconnection',
            name='aap_setting_mailbox_bb6893_idx',
        ),
        migrations.RemoveConstraint(
            model_name='mailboxconnection',
            name='aap_settings_mailbox_conn_kind_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='mailbox',
            name='aap_settings_mailbox_email_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='providerpreset',
            name='aap_settings_provider_preset_code_kind_uniq',
        ),
        migrations.RemoveIndex(
            model_name='providerpreset',
            name='aap_setting_is_acti_53112a_idx',
        ),
        migrations.RemoveIndex(
            model_name='providerpreset',
            name='aap_setting_code_50c70c_idx',
        ),
        migrations.AddField(
            model_name='providerpreset',
            name='preset_json',
            field=models.JSONField(default=dict, help_text='Произвольные подсказки для UI (host/ports/tls/oauth_hint/etc.)'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='workspace_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mailboxoauthapp',
            name='client_secret_enc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailboxoauthapp',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mailboxoauthapp',
            name='workspace_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sendingsettings',
            name='value_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sendingsettings',
            name='workspace_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'email'), name='aap_settings_mailbox_ws_email_uniq'),
        ),
        migrations.AddField(
            model_name='imapmailbox',
            name='mailbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imap', to='aap_settings.mailbox'),
        ),
        migrations.AddField(
            model_name='smtpmailbox',
            name='mailbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp', to='aap_settings.mailbox'),
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='limit_hour_sent',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='code',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='extra_json',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='host',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='ports_json',
        ),
        migrations.RemoveField(
            model_name='providerpreset',
            name='security',
        ),
        migrations.DeleteModel(
            name='MailboxConnection',
        ),
    ]
