# Generated by Django 6.0 on 2026-01-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0009_imapmailbox_smtpmailbox_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mailboxoauthapp',
            name='aap_setting_workspa_149e4f_idx',
        ),
        migrations.RemoveConstraint(
            model_name='mailboxoauthapp',
            name='aap_settings_oauth_app_ws_provider_uniq',
        ),
        migrations.DeleteModel(
            name='MailboxOAuthApp',
        ),
    ]
