# Generated by Django 6.0 on 2026-01-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0010_remove_mailboxoauthapp_aap_setting_workspa_149e4f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imapmailbox',
            name='auth_type',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('GOOGLE_OAUTH_2_0', 'GOOGLE_OAUTH_2_0'), ('MICROSOFT_OAUTH_2_0', 'MICROSOFT_OAUTH_2_0')], default='LOGIN', max_length=32),
        ),
        migrations.AlterField(
            model_name='providerpreset',
            name='preset_json',
            field=models.JSONField(default=dict, help_text='Произвольные подсказки для UI (smtp/imap host/ports/security/auth_type/oauth_hint/etc.)'),
        ),
        migrations.AlterField(
            model_name='smtpmailbox',
            name='auth_type',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('GOOGLE_OAUTH_2_0', 'GOOGLE_OAUTH_2_0'), ('MICROSOFT_OAUTH_2_0', 'MICROSOFT_OAUTH_2_0')], default='LOGIN', max_length=32),
        ),
    ]
