# Generated by Django 6.0 on 2026-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_settings', '0011_mailbox_archived_alter_imapmailbox_auth_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPresetNoAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preset_json', models.JSONField(default=dict, help_text='Произвольные подсказки для UI (smtp relay noauth host/ports/security/auth_type/etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'aap_settings_provider_presets_noauth',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='smtpmailbox',
            name='auth_type',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('RELAY_NOAUTH', 'RELAY_NOAUTH'), ('GOOGLE_OAUTH_2_0', 'GOOGLE_OAUTH_2_0'), ('MICROSOFT_OAUTH_2_0', 'MICROSOFT_OAUTH_2_0')], default='LOGIN', max_length=32),
        ),
    ]
