# FILE: web/panel/aap_settings/migrations/0013_workspacedomain.py
# DATE: 2026-03-19
# PURPOSE: Add WorkspaceDomain model for client domains inside panel settings.

# Generated by Django 6.0 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aap_settings", "0012_providerpresetnoauth_alter_smtpmailbox_auth_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "aap_settings_workspace_domains",
                "ordering": ["domain", "id"],
                "indexes": [models.Index(fields=["workspace_id", "created_at"], name="aap_setting_workspa_6fb126_idx")],
            },
        ),
    ]
