# Generated by Django 6.0 on 2026-04-09

from django.db import migrations, models
import panel.aap_settings.models


DEFAULT_GLOBAL_GLOBAL_WINDOW = {
    "mon": [],
    "tue": [{"from": "08:30", "to": "12:30"}],
    "wed": [{"from": "08:30", "to": "12:30"}],
    "thu": [{"from": "08:30", "to": "12:30"}],
    "fri": [],
    "sat": [],
    "sun": [],
    "hol": [],
}


def seed_global_global_window(apps, schema_editor):
    GlobalSendingSettings = apps.get_model("aap_settings", "GlobalSendingSettings")
    obj, _ = GlobalSendingSettings.objects.get_or_create(
        singleton_key=1,
        defaults={"global_global_window": DEFAULT_GLOBAL_GLOBAL_WINDOW},
    )
    cur = obj.global_global_window if isinstance(obj.global_global_window, dict) else {}
    if not cur:
        obj.global_global_window = DEFAULT_GLOBAL_GLOBAL_WINDOW
        obj.save(update_fields=["global_global_window", "updated_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("aap_settings", "0013_workspacedomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSendingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                (
                    "global_global_window",
                    models.JSONField(blank=True, default=panel.aap_settings.models.default_global_global_window_json),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "aap_settings_global_sending_settings",
            },
        ),
        migrations.RunPython(seed_global_global_window, noop_reverse),
    ]
