# Generated by Django 6.0 on 2026-04-13 00:00

import django.core.validators
from django.db import migrations, models


def _copy_limit_hour_from_smtp(apps, schema_editor):
    schema_editor.execute(
        """
        UPDATE aap_settings_mailboxes AS mb
        SET limit_hour = LEAST(120, GREATEST(0, sm.limit_hour_sent))
        FROM aap_settings_smtp_mailboxes AS sm
        WHERE sm.mailbox_id = mb.id
        """
    )


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("aap_settings", "0014_globalsendingsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="limit_day",
            field=models.PositiveIntegerField(
                default=500,
                validators=[django.core.validators.MaxValueValidator(1000)],
            ),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="limit_hour",
            field=models.PositiveIntegerField(
                default=60,
                validators=[django.core.validators.MaxValueValidator(120)],
            ),
        ),
        migrations.RunPython(_copy_limit_hour_from_smtp, _noop_reverse),
        migrations.RemoveField(
            model_name="smtpmailbox",
            name="limit_hour_sent",
        ),
    ]
