# Generated by Django 6.0 on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aap_settings", "0015_mailbox_limits_to_mailbox"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkspaceDomain",
        ),
    ]
