# Generated by Django 6.0 on 2026-01-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('template_name', models.CharField(help_text='Имя/код шаблона', max_length=255)),
                ('template_html', models.TextField(blank=True, default='', help_text='HTML шаблона (большой)')),
                ('styles', models.JSONField(blank=True, default=dict, help_text='Стили/настройки (JSON)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns_templates',
                'ordering': ['order', 'template_name'],
                'indexes': [models.Index(fields=['workspace_id', 'is_active', 'order'], name='campaigns_t_workspa_10e6b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'template_name'), name='uq_campaigns_templates_ws_name')],
            },
        ),
    ]
