# Generated by Django 6.0 on 2026-01-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_campaigns', '0001_initial'),
        ('aap_lists', '0002_mailinglist_archived'),
        ('aap_settings', '0004_sendingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='styles',
            field=models.JSONField(blank=True, default=dict, help_text='Стили (JSON)'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='template_html',
            field=models.TextField(blank=True, default='', help_text='HTML шаблона'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(help_text='Название кампании', max_length=255)),
                ('send_after_parent_days', models.PositiveIntegerField(default=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('window', models.JSONField(blank=True, default=dict, help_text='Окно отправки (override глобальных настроек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='aap_campaigns.campaign')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='aap_settings.mailbox')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='aap_lists.mailinglist')),
            ],
            options={
                'db_table': 'campaigns_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('html_content', models.TextField(blank=True, default='')),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('ready_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='aap_campaigns.campaign')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='aap_campaigns.templates')),
            ],
            options={
                'db_table': 'campaigns_letters',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace_id', 'active', 'start_at'], name='campaigns_c_workspa_0ba5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace_id', 'campaign_parent'], name='campaigns_c_workspa_174219_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['workspace_id'], name='campaigns_l_workspa_952dbd_idx'),
        ),
    ]
