# Generated by Django 6.0 on 2026-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_campaigns', '0002_alter_templates_styles_alter_templates_template_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
