# Generated by Django 6.0 on 2026-04-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aap_audience", "0011_remove_audiencetask_collected_and_more"),
        ("aap_lists", "0001_initial"),
        ("aap_campaigns", "0003_templates_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="mailing_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="aap_lists.mailinglist",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="sending_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="aap_audience.audiencetask",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="user_active",
            field=models.BooleanField(default=True),
        ),
    ]
