# Generated by Django 6.0 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aap_campaigns", "0004_campaign_sending_list_and_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="sending_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="sent_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="to_send_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
