# Generated by Django 6.0 on 2026-02-22 15:05

from django.db import migrations


FORWARD_SQL = """
INSERT INTO public_clientuser (
    id,
    password,
    last_login,
    is_superuser,
    username,
    first_name,
    last_name,
    email,
    is_staff,
    is_active,
    date_joined
)
SELECT
    id,
    password,
    last_login,
    is_superuser,
    username,
    first_name,
    last_name,
    email,
    is_staff,
    is_active,
    date_joined
FROM auth_user
ON CONFLICT (id) DO NOTHING;

INSERT INTO public_clientuser_groups (clientuser_id, group_id)
SELECT aug.user_id, aug.group_id
FROM auth_user_groups aug
JOIN public_clientuser cu ON cu.id = aug.user_id
ON CONFLICT DO NOTHING;

INSERT INTO public_clientuser_user_permissions (clientuser_id, permission_id)
SELECT aup.user_id, aup.permission_id
FROM auth_user_user_permissions aup
JOIN public_clientuser cu ON cu.id = aup.user_id
ON CONFLICT DO NOTHING;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM aap_audience_audiencetask t
        LEFT JOIN public_clientuser cu ON cu.id = t.user_id
        WHERE cu.id IS NULL
    ) THEN
        RAISE EXCEPTION 'aap_audience_audiencetask has user_id not present in public_clientuser';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM aap_lists_mailinglist t
        LEFT JOIN public_clientuser cu ON cu.id = t.user_id
        WHERE cu.id IS NULL
    ) THEN
        RAISE EXCEPTION 'aap_lists_mailinglist has user_id not present in public_clientuser';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM accounts_userworkspace t
        LEFT JOIN public_clientuser cu ON cu.id = t.user_id
        WHERE cu.id IS NULL
    ) THEN
        RAISE EXCEPTION 'accounts_userworkspace has user_id not present in public_clientuser';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM accounts_frontuser t
        LEFT JOIN public_clientuser cu ON cu.id = t.user_id
        WHERE cu.id IS NULL
    ) THEN
        RAISE EXCEPTION 'accounts_frontuser has user_id not present in public_clientuser';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM crawl_tasks t
        LEFT JOIN public_clientuser cu ON cu.id = t.user_id
        WHERE cu.id IS NULL
    ) THEN
        RAISE EXCEPTION 'crawl_tasks has user_id not present in public_clientuser';
    END IF;
END
$$;

ALTER TABLE aap_audience_audiencetask DROP CONSTRAINT IF EXISTS aap_audience_audiencetask_user_id_47b3d7db_fk_auth_user_id;
ALTER TABLE aap_audience_audiencetask DROP CONSTRAINT IF EXISTS aap_audience_audiencetask_user_id_fkey;
ALTER TABLE aap_audience_audiencetask
    ADD CONSTRAINT aap_audience_audiencetask_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public_clientuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE aap_lists_mailinglist DROP CONSTRAINT IF EXISTS aap_lists_mailinglist_user_id_f1554b53_fk_auth_user_id;
ALTER TABLE aap_lists_mailinglist DROP CONSTRAINT IF EXISTS aap_lists_mailinglist_user_id_fkey;
ALTER TABLE aap_lists_mailinglist
    ADD CONSTRAINT aap_lists_mailinglist_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public_clientuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE accounts_frontuser DROP CONSTRAINT IF EXISTS accounts_frontuser_user_id_d5d2b49c_fk_auth_user_id;
ALTER TABLE accounts_frontuser DROP CONSTRAINT IF EXISTS accounts_frontuser_user_id_fkey;
ALTER TABLE accounts_frontuser
    ADD CONSTRAINT accounts_frontuser_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public_clientuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE accounts_userworkspace DROP CONSTRAINT IF EXISTS accounts_userworkspace_user_id_6a0fe089_fk_auth_user_id;
ALTER TABLE accounts_userworkspace DROP CONSTRAINT IF EXISTS accounts_userworkspace_user_id_fkey;
ALTER TABLE accounts_userworkspace
    ADD CONSTRAINT accounts_userworkspace_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public_clientuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE crawl_tasks DROP CONSTRAINT IF EXISTS crawl_tasks_user_id_fkey;
ALTER TABLE crawl_tasks
    ADD CONSTRAINT crawl_tasks_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public_clientuser(id) DEFERRABLE INITIALLY DEFERRED;

DELETE FROM auth_user_groups;
DELETE FROM auth_user_user_permissions;
DELETE FROM django_admin_log;
DELETE FROM auth_user;

SELECT setval(
    pg_get_serial_sequence('public_clientuser', 'id'),
    COALESCE((SELECT MAX(id) FROM public_clientuser), 1),
    true
);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=migrations.RunSQL.noop),
    ]
