# Generated by Django 6.0 on 2026-02-22 23:15

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_move_client_users_and_switch_fks'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
