# Generated by Django 6.0 on 2026-02-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_alter_clientuser_managers"),
        ("mailer_web", "0002_rehome_clientuser_table"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="ClientUser"),
            ],
            database_operations=[],
        ),
    ]
