# FILE: config/nginx/conf.d/41-bergenimmobilienservice.conf
# DATE: 2026-03-05
# PURPOSE: bergenimmobilienservice.de domains redirects with ACME on :80.

server {
    listen 80;
    listen [::]:80;
    server_name bergenimmobilienservice.de www.bergenimmobilienservice.de;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name bergenimmobilienservice.de www.bergenimmobilienservice.de;

    ssl_certificate     /etc/letsencrypt/live/bergenimmobilienservice.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bergenimmobilienservice.de/privkey.pem;

    return 301 https://www.bergen-immobilienservice.com$request_uri;
}
